export var rundownDataColumn = {
  rNlevel: {
    index: 0,
    name: "rNlevel",
    show: true,
    label: "ContentStatus",
    width: 80,
  },
  rPage: { index: 1, name: "rPage", show: true, label: "Page", width: 60 },
  SopperCode: { index: 2, name: "SopperCode", show: true, label: "", width: 26 },
  CCode: { index: 3, name: "CCode", show: true, label: "C-Code", width: 26 },
  rStorySlug: {
    index: 4,
    name: "rStorySlug",
    show: true,
    label: "Story Subject >> Slug",
    width: 220,
  },
  CCode2: { index: 5, name: "CCode2", show: true, label: "", width: 26 },
  rSegment: { index: 6, name: "rSegment", show: true, label: "Segment", width: 80 },
  rNewsFormat: {
    index: 7,
    name: "rNewsFormat",
    show: true,
    label: "News Format",
    width: 100,
  },
  rWith: { index: 8, name: "rWith", show: true, label: ">With>>", width: 130 },
  rBreakStatus: { index: 9, name: "rBreakStatus", show: true, label: "Break", width: 50 },
  rFinalApproval: {
    index: 10,
    name: "rFinalApproval",
    show: true,
    label: "Final Appr",
    width: 50,
  },
  rSpecialNotes: {
    index: 11,
    name: "rSpecialNotes",
    show: true,
    label: "Special Notes",
    width: 130,
  },
  rDuration: { index: 12, name: "rDuration", show: true, label: "Duration", width: 65 },
  Start: { index: 13, name: "Start", show: true, label: "Start", width: 65 },
  End: { index: 14, name: "End", show: true, label: "End", width: 65 },
  Sum: { index: 15, name: "Sum", show: true, label: "Sum", width: 65 },
  rRemaining: {
    index: 16,
    name: "rRemaining",
    show: true,
    label: "Remaining",
    width: 65,
  },

  rLastModBy: {
    index: 17,
    name: "rLastModBy",
    show: true,
    label: "Last Mod By",
    width: 130,
  },
  rDetailStory: {
    index: 18,
    name: "rDetailStory",
    show: false,
    label: "Detail Story",
    width: 0,
  },
  rid: { index: 19, name: "rid", show: false, label: "ID", width: 0 },

  rAiredStatus: {
    index: 20,
    name: "rAiredStatus",
    show: true,
    label: "Aired Status",
    width: 50,
  }, //means anchor is reading
  rAnchorName: {
    index: 21,
    name: "rAnchorName",
    show: true,
    label: "AnchorName",
    width: 80,
  },
  rUploadFileSerilize: {
    index: 22,
    name:"rUploadFileSerilize",
    show: false,
    label: "UploadFileSerilize",
    width: 0,
  },
  SopperAvailable: {
    index: 23,
    name: "SopperAvailable",
    show: false,
    label: "SopperAvailable",
    width: 0,
  },
};
