export const LOGIN_USERNAME = "LOGIN_USERNAME";
export const LOGIN_PASSWORD = "LOGIN_PASSWORD";
export const LOGIN_REDIRECT_TO_PATH = "LOGIN_REDIRECT_TO_PATH";
export const LOGIN_IS_LOADING = "LOGIN_IS_LOADING";
export const LOGIN_REGISTER_TOGGLE_FORM_NAME = "LOGIN_REGISTER_TOGGLE_FORM_NAME";
export const LOGIN_USER_AUTHENTICATED = "LOGIN_USER_AUTHENTICATED";

export const REGISTER_FULLNAME = "REGISTER_FULLNAME";
export const REGISTER_CITY = "REGISTER_CITY";
export const REGISTER_MOBILE = "REGISTER_MOBILE";
export const REGISTER_EMAIL = "REGISTER_EMAIL";
export const REGISTER_CHANNELNAME = "REGISTER_CHANNELNAME";

export const DIALOG_OPEN = "DIALOG_OPEN";
export const DIALOG_CANCEL_TEXT = "DIALOG_CANCEL_TEXT";
export const DIALOG_OK_TEXT = "DIALOG_OK_TEXT";
export const DIALOG_TITLE = "DIALOG_TITLE";
export const DIALOG_CONTENT = "DIALOG_CONTENT";
export const DIALOG_OK_CLICK = "DIALOG_OK_CLICK";

export const HEADER_OPEN_DRAWER = "HEADER_OPEN_DRAWER";
export const HEADER_DRAWER_TOP_CONTAINER_HEIGHT = "HEADER_DRAWER_TOP_CONTAINER_HEIGHT";
export const HEADER_DRAWER_BOTTOM_CONTAINER_HEIGHT = "HEADER_DRAWER_BOTTOM_CONTAINER_HEIGHT";
export const HEADER_ANCHOR_EL = "HEADER_ANCHOR_EL";

export const CHANGE_PASSWORD_MODAL_TOGGLE = "CHANGE_PASSWORD_MODAL_TOGGLE";
export const CHANGE_PASSWORD_IS_LOADING = "CHANGE_PASSWORD_IS_LOADING";
export const CHANGE_PASSWORD_OLD_PASSWORD = "CHANGE_PASSWORD_OLD_PASSWORD";
export const CHANGE_PASSWORD_NEW_PASSWORD = "CHANGE_PASSWORD_NEW_PASSWORD";

export const LAST_FETCH_FOLDER_DATA = "LAST_FETCH_FOLDER_DATA";

export const USER_PANEL_NAVBAR_HEIGHT = "USER_PANEL_NAVBAR_HEIGHT";
export const USER_PANEL_WINDOW_SIZE = "USER_PANEL_WINDOW_SIZE";
export const USER_PANEL_TITLE_CONTAINER_HEIGHT = "USER_PANEL_TITLE_CONTAINER_HEIGHT";
export const USER_PANEL_LOGOUT = "USER_PANEL_LOGOUT";
export const USER_PANEL_REDIRECT_TO_PATH = "LOGIN_REDIRECT_TO_PATH";

export const TREE_VIEW_DATA = "TREE_VIEW_DATA";
export const TREE_VIEW_DATA_CLONE = "TREE_VIEW_DATA_CLONE";
export const TREE_VIEW_SELECTED_FOLDER_ID = "TREE_VIEW_SELECTED_FOLDER_ID";
export const TREE_VIEW_LOADING = "TREE_VIEW_LOADING";
export const TREE_VIEW_SELECTED_ITEM_INFO = "TREE_VIEW_SELECTED_ITEM_INFO";
export const TREE_VIEW_TOGGLE_GROUP_VIEW = "TREE_VIEW_TOGGLE_GROUP_VIEW";
export const TREE_VIEW_FONT_SIZE = "TREE_VIEW_FONT_SIZE";

export const CRUD_SEARCH_INPUT_TEXT = "CRUD_SEARCH_INPUT_TEXT";
export const CRUD_SEARCH_TEXT_TYPE = "CRUD_SEARCH_TEXT_TYPE";
export const CRUD_ARCHIVE_SEARCH_MODAL_TOGGLE = "CRUD_ARCHIVE_SEARCH_MODAL_TOGGLE";
export const CRUD_ARCHIVE_DATE_TYPE_MODAL = "CRUD_ARCHIVE_DATE_TYPE_MODAL";
export const CRUD_RESET_SEARCH = "CRUD_RESET_SEARCH";
export const CRUD_PANEL_HEIGHT = "CRUD_PANEL_HEIGHT";
export const CRUD_ARCHIVE_DATE_INPUT = "CRUD_ARCHIVE_DATE_INPUT";
export const CRUD_ALL_FOLDER_SEARCH_CALENDER_MODAL = "CRUD_ALL_FOLDER_SEARCH_CALENDER_MODAL";
export const CRUD_ALL_FOLDER_SEARCH_INPUT_TEXT = "CRUD_ALL_FOLDER_SEARCH_INPUT_TEXT";
export const CRUD_ALL_FOLDER_SEARCH_TEXT = "CRUD_ALL_FOLDER_SEARCH_TEXT";
export const CRUD_ALL_FOLDER_SEARCH_DATE_INPUT = "CRUD_ALL_FOLDER_SEARCH_DATE_INPUT";
export const CRUD_ALL_FOLDER_TEXT_DATE_TYPE_MODAL = "CRUD_ALL_FOLDER_TEXT_DATE_TYPE_MODAL";



export const EDITOR_VIEW_REPORT_SOPPER_LOADING = "EDITOR_VIEW_REPORT_SOPPER_LOADING";
export const EDITOR_VIEW_REPORT_SOPPER_STATUS = "EDITOR_VIEW_REPORT_SOPPER_STATUS";
export const EDITOR_VIEW_SOPPER_MODAL_TOGGLE = "EDITOR_VIEW_SOPPER_MODAL_TOGGLE";
export const EDITOR_VIEW_SOPPER_MODAL_LOADING = "EDITOR_VIEW_SOPPER_MODAL_LOADING";
export const EDITOR_VIEW_MODIFICATION_DETAILS_MODAL_TOGGLE = "EDITOR_VIEW_MODIFICATION_DETAILS_MODAL_TOGGLE";
export const EDITOR_VIEW_SOPPER_MODAL_TEXT = "EDITOR_VIEW_SOPPER_MODAL_TEXT";
export const EDITOR_VIEW_MAIN_TOP_PANEL_HEIGHT = "EDITOR_VIEW_MAIN_TOP_PANEL_HEIGHT";
export const EDITOR_VIEW_SCROLL_AVAILABLE = "EDITOR_VIEW_SCROLL_AVAILABLE";
export const EDITOR_VIEW_FONT_SIZE = "EDITOR_VIEW_FONT_SIZE";

export const MEDIA_PLAYER_MODAL_FILES = "MEDIA_PLAYER_MODAL_FILES";
export const MEDIA_PLAYER_MODAL_TOGGLE = "MEDIA_PLAYER_MODAL_TOGGLE";
export const MEDIA_PLAYER_MODAL_SELECTED_FILE = "MEDIA_PLAYER_MODAL_SELECTED_FILE";
export const MEDIA_IMAGE_CONTAINER_WIDTH = "MEDIA_IMAGE_CONTAINER_WIDTH";
export const MEDIA_DOWNLOAD_INFO = "MEDIA_DOWNLOAD_INFO";

export const SOPPER_MODAL_TOGGLE = "SOPPER_MODAL_TOGGLE";
export const SOPPER_MODAL_TEXT = "SOPPER_MODAL_TEXT";
export const SOPPER_MODAL_TEXT_LOADING = "SOPPER_MODAL_TEXT_LOADING";

export const MOD_DETAILS_MODAL_TOGGLE = "MOD_DETAILS_MODAL_TOGGLE";
export const MOD_DETAILS_MODAL_LOADING = "MOD_DETAILS_MODAL_LOADING";
export const MOD_DETAILS_MODAL_TITLE = "MOD_DETAILS_MODAL_TITLE";
export const MOD_DETAILS_MODAL_CONTENT_TEXT = "MOD_DETAILS_MODAL_CONTENT_TEXT";
export const MOD_DETAILS_MODAL_READ_DETAILS = "MOD_DETAILS_MODAL_READ_DETAILS";
export const MOD_DETAILS_MODAL_READ_DETAILS_CONTAINER_TOGGLE = "MOD_DETAILS_MODAL_READ_DETAILS_CONTAINER_TOGGLE";
export const MOD_DETAILS_MODAL_CORRECTION_DETAILS = "MOD_DETAILS_MODAL_CORRECTION_DETAILS";
export const MOD_DETAILS_MODAL_CORRECTION_DETAILS_CONTAINER_TOGGLE = "MOD_DETAILS_MODAL_CORRECTION_DETAILS_CONTAINER_TOGGLE";
export const MOD_DETAILS_MODAL_ARROW_PREVIOUS_ACTIVE = "MOD_DETAILS_MODAL_ARROW_PREVIOUS_ACTIVE";
export const MOD_DETAILS_MODAL_ARROW_NEXT_ACTIVE = "MOD_DETAILS_MODAL_ARROW_NEXT_ACTIVE";
export const MOD_DETAILS_MODAL_RESET = "MOD_DETAILS_MODAL_RESET";

export const RUNDOWN_LOADING = "RUNDOWN_LOADING";
export const RUNDOWN_DATA = "RUNDOWN_DATA";
export const RUNDOWN_TABLE_DATA = "RUNDOWN_TABLE_DATA";
export const RUNDOWN_SELECTED_ITEM_DATA = "RUNDOWN_SELECTED_ITEM_DATA";
export const RUNDOWN_HEADER_TEXT = "RUNDOWN_HEADER_TEXT";
export const RUNDOWN_MAIN_TOP_PANEL_HEIGHT = "RUNDOWN_MAIN_TOP_PANEL_HEIGHT";
export const RUNDOWN_FONT_SIZE = "RUNDOWN_FONT_SIZE";

export const SWITCH_ACCOUNT_MODAL_TOGGLE = "SWITCH_ACCOUNT_MODAL_TOGGLE";
export const SWITCH_ACCOUNT_MODAL_SEARCH_TEXT_INPUT = "SWITCH_ACCOUNT_MODAL_SEARCH_TEXT_INPUT";
export const SWITCH_ACCOUNT_MODAL_SEARCH_TEXT = "SWITCH_ACCOUNT_MODAL_SEARCH_TEXT";
export const SWITCH_ACCOUNT_MODAL_TABLE_DATA = "SWITCH_ACCOUNT_MODAL_TABLE_DATA";
export const SWITCH_ACCOUNT_MODAL_LOADING = "SWITCH_ACCOUNT_MODAL_LOADING";
export const SWITCH_ACCOUNT_MODAL_SELECTED_USER = "SWITCH_ACCOUNT_SELECTED_USER";
export const SWITCH_ACCOUNT_MODAL_MAIN_TOP_CONTAINER_HEIGHT = "SWITCH_ACCOUNT_MODAL_MAIN_TOP_CONTAINER_HEIGHT";
export const SWITCH_ACCOUNT_MODAL_SEARCH_TABLE_DATA = "SWITCH_ACCOUNT_MODAL_SEARCH_TABLE_DATA";
export const SWITCH_ACCOUNT_MODAL_RESET = "SWITCH_ACCOUNT_MODAL_RESET";

export const SAVE_AS_MODAL_TOGGLE = "SAVE_AS_MODAL_TOGGLE";
export const SAVE_AS_MODAL_SELECTED_FOLDER_INFO = "SAVE_AS_SELECTED_FOLDER_INFO";
export const SAVE_AS_MODAL_RADIO_DATA = "SAVE_AS_MODAL_RADIO_DATA";
export const SAVE_AS_MODAL_RADIO_MAIN_TOP_CONTAINER_HEIGHT = "SAVE_AS_MODAL_RADIO_MAIN_TOP_CONTAINER_HEIGHT";
export const SAVE_AS_MODAL_RADIO_MAIN_BOTTOM_CONTAINER_HEIGHT = "SAVE_AS_MODAL_RADIO_MAIN_BOTTOM_CONTAINER_HEIGHT";
export const SAVE_AS_MODAL_LOADING = "SAVE_AS_MODAL_LOADING";

export const DELETE_ITEM_BUTTON_LOADING = "DELETE_ITEM_BUTTON_LOADING";

export const ADD_ITEM_MODAL_TOGGLE = "ADD_ITEM_MODAL_TOGGLE";
export const ADD_ITEM_MODAL_LOADING = "ADD_ITEM_MODAL_LOADING";
export const ADD_ITEM_MODAL_SELECTED_FOLDER_ID = "ADD_ITEM_MODAL_SELECTED_FOLDER_ID";
export const ADD_ITEM_MODAL_FOLDER_DATA = "ADD_ITEM_MODAL_FOLDER_DATA";
export const ADD_ITEM_MODAL_SUBJECT = "ADD_ITEM_MODAL_SUBJECT"; 
export const ADD_ITEM_MODAL_CONTENT = "ADD_ITEM_MODAL_CONTENT"; 
export const ADD_ITEM_MODAL_RESET = "ADD_ITEM_MODAL_RESET";
export const ADD_ITEM_MODAL_MAIN_TOP_CONTAINER_HEIGHT = "ADD_ITEM_MODAL_MAIN_TOP_CONTAINER_HEIGHT";
export const ADD_ITEM_MODAL_MAIN_MIDDLE_CONTAINER_HEIGHT = "ADD_ITEM_MODAL_MAIN_MIDDLE_CONTAINER_HEIGHT";
export const ADD_ITEM_MODAL_MAIN_BOTTOM_CONTAINER_HEIGHT = "ADD_ITEM_MODAL_MAIN_BOTTOM_CONTAINER_HEIGHT";

export const UPLOAD_ATTACHMENTS_MODAL_TOGGLE = "UPLOAD_ATTACHMENTS_MODAL_TOGGLE";
export const UPLOAD_ATTACHMENTS_MODAL_FILES_DATA = "UPLOAD_ATTACHMENTS_MODAL_FILES_DATA";
export const UPLOAD_ATTACHMENTS_MODAL_RESET = "UPLOAD_ATTACHMENTS_MODAL_RESET";

export const EDIT_ITEM_MODAL_TOGGLE = "EDIT_ITEM_MODAL_TOGGLE";
export const EDIT_ITEM_MODAL_LOADING = "EDIT_ITEM_MODAL_LOADING";
export const EDIT_ITEM_MODAL_FOLDER_DATA = "EDIT_ITEM_MODAL_FOLDER_DATA";
export const EDIT_ITEM_MODAL_SUBJECT = "EDIT_ITEM_MODAL_SUBJECT"; 
export const EDIT_ITEM_MODAL_CONTENT = "EDIT_ITEM_MODAL_CONTENT"; 
export const EDIT_ITEM_MODAL_RESET = "EDIT_ITEM_MODAL_RESET";
export const EDIT_ITEM_MODAL_MAIN_TOP_CONTAINER_HEIGHT = "EDIT_ITEM_MODAL_MAIN_TOP_CONTAINER_HEIGHT";
export const EDIT_ITEM_MODAL_MAIN_MIDDLE_CONTAINER_HEIGHT = "EDIT_ITEM_MODAL_MAIN_MIDDLE_CONTAINER_HEIGHT";
export const EDIT_ITEM_MODAL_MAIN_BOTTOM_CONTAINER_HEIGHT = "EDIT_ITEM_MODAL_MAIN_BOTTOM_CONTAINER_HEIGHT";

export const CAMERA_MODAL_TOGGLE = "CAMERA_MODAL_TOGGLE";
